### PR TITLE
DM-5943: Add software versioning provenance to QA tables

### PR DESCRIPTION
**Pull request by jonathansick**
This PR principally adds a `VersionedPackage` model. Each job relates to many `VersionedPackage` objects that identify specific EUPS packages and their versions that were used during a QA run. This will allow us to plot QA metrics versus git commits. Note that this is not a full software provenance system; the complete state of the LSST Science Pipelines is not unambiguously determined by the git commit hashes of each individual package. It does, however, help us out.

The VersionedPackage objects are populated during POSTS to the `/job/` endpoint using the `packages` field. (`VersionedPackageSerializer` is a nested serializer to `JobSerializer`).

The Job JSON looks something like

```
{
    ...
    "packages": [
        {
            "name": "afw",
            "git_url": "http://github.com/lsst/afw.git",
            "git_commit": "a7aa450f60375473c010319e56db559457b43f9a",
            "git_branch": "master",
            "build_version": "b1"
        }
    ]
}
```

This PR also adds several general API/code improvements

1. Help text for columns to improve documentation
2. Make API endpoints plural, following popular conventions. e.g. `/metrics/` and `/jobs/`
3. Rename the field `Job.url` to `Job.ci_url` to prevent a bug where Django REST API would attempt to cleverly, but incorrectly, set the `location` HTTP header to the value of `Job.url`.

Finally, you might be wondering why `VersionedPackage` did not refactor the name and repo URL of EUPS packages into its own table. I tried this. Essentially Jobs would be in a many-to-many relationship with a Packages table. I build a PackageVersion 'through' table as an intermediary. In the end, I simply couldn't persist the package version data with a nested serialization in the Job serializer using Django REST API. The current solution creates some additional duplication of data (Package name and URL), but functionally will still work. I wouldn't recommend revising the many-to-many approach unless you know what you're doing with Django REST Framework.

### CODE REVIEW

**Comment by afausti** [comment]
@jonathansick I have noticed you changed the name of field runtime to date in the Job model. That's fine, but you forgot to make this change in the Jobserializer().  I am getting an error trying to access the API.

**Comment by afausti** [comment]
The same is true for Job.ci_url

**Comment by jonathansick** [comment]
Thanks, I've fixed that. (Gotta put in py.test tests for Travis CI)

**Comment by afausti** [comment]
Great thanks, for now I have simple tests under tests/test_api.py  you can change test_post_job()

**Comment by jonathansick** [comment]
Oh nice. Is there a command to run these tests?

**Comment by afausti** [comment]
Under  qa-dashboard/squash just type py.test, will include that in the README

**Comment by jonathansick** [comment]
Oh cool. I'll setup Travis then (will add to this PR).

**Comment by afausti** [comment]
@jonathansick successfully tested a job post request using the JSON below.

I think the implementation of a single model VersionedPackage is simpler and interesting because we dont have to initialize a 'Package' table.

I noticed the phe post request works if either measurements or packages lists are empty. I think that's fine.

So I think it is all good if you want to merge this ticket branch to master. 

```
{
    "name": "ci_cfht",
    "build": "1",
    "date": "2016-05-13T23:26:43.785264Z",
    "ci_url": "https://ci.lsst.codes/job/ci_cfht/1/",
    "status": 0,
    "measurements": [
        {
            "metric": "PA1",
            "value": 5.0
        }
    ],
    "packages": [
        {
            "name": "afw",
            "git_url": "http://github.com/lsst/afw.git",
            "git_commit": "a7aa450f60375473c010319e56db559457b43f9a",
            "git_branch": "master",
            "build_version": "b1"
        }
    ],
    "links": {
        "self": "http://localhost:8000/api/jobs/2/"
    }
}
```

**Comment by jonathansick** [comment]
Thanks @afausti. Merging this now. Note that this doesn't include additional API/model updates from https://community.lsst.org/t/json-schema-for-squash/777?u=jsick.

I also think we'll need to put more work into the testing strategy. For example, we probably want every test to run its own isolated app and database so there isn't DB cross-talk between tests.

**Pull request merged**
